language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install typescript -g
  - npm install gulp -g
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run test
after_script:
  - npm run coverage
  - npm run coveralls
  - npm run codeclimate