language: node_js
node_js:
  - "0.10"
before_install:
  - npm install typescript -g
  - npm install gulp -g
install:
  - npm install
  - npm update
before_script:
  - npm run build
script:
  - npm run test-ci
after_script:
  - npm run coverage
  - npm run coveralls
  - npm run codeclimate