language: node_js
node_js:
  - "0.12"
before_install:
  - npm install typescript -g
  - npm install gulp -g
before_script:
  - npm run compile
after_script:
  - npm run coverage
  - npm run coveralls
  - npm run codeclimate