language: node_js
node_js:
  - "5.12.0"
  - "6.6.0"
  - "7.7.3"
before_install:
  - npm install typescript -g
  - npm install gulp -g
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run test
after_script:
  - npm run coverage
  - npm run coveralls
  - npm run codeclimate