# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# branches to build
branches:
  # whitelist
  only:
    - master

# build version format
version: "{build}"

# what combinations to test
environment:

  matrix:
    # node.js
    - nodejs_version: "4.0"
platform:
  - x86
  - x64


# Get the stable version of node
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install typescript -g
  - npm install gulp -g

build: off

test_script:
  - node --version
  - npm --version
  - PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\npm\tsc
  - tsc -help
  - C:\Users\appveyor\AppData\Roaming\npm\tsc -help
  - cmd: npm run build
  - cmd: npm run test-ci